# Generated by Django 3.0.6 on 2020-06-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auser',
            name='phone_num',
            field=models.IntegerField(null=True),
        ),
    ]
